In [23]:
import tensorflow as tf
import numpy as np

x1 = np.arange(12.0).reshape((3, 4))
x2 = np.arange(20.0).reshape((4,5))
x3 = np.arange(5.0).reshape((1,5))
print x1, '\n', x2, '\n', x3, '\n', np.matmul(x1, x2), '\n', np.add(np.matmul(x1, x2), x3)

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]] 
[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]] 
[[ 0.  1.  2.  3.  4.]] 
[[  70.   76.   82.   88.   94.]
 [ 190.  212.  234.  256.  278.]
 [ 310.  348.  386.  424.  462.]] 
[[  70.   77.   84.   91.   98.]
 [ 190.  213.  236.  259.  282.]
 [ 310.  349.  388.  427.  466.]]


In [32]:
a = [1, 2, 3, 4]
#print a[2:]

for i in a[4:]:
    print i

In [34]:
a=[]
print a[0]

IndexError: list index out of range

In [31]:
a[0]

1